package com.menglin.dao;

import com.menglin.entity.MajorCourse;
import org.apache.ibatis.annotations.Param;

public interface MajorCourseDao {

    MajorCourse selectByMajorIdAndCourseId(@Param("majorId") Long majorId, @Param("courseId") Long courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insert(MajorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insertSelective(MajorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    MajorCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKeySelective(MajorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKey(MajorCourse record);
}