package com.menglin.dao;

import com.menglin.entity.Major;

import java.util.List;
import java.util.Map;

public interface MajorDao {

    Major selectByName(String name);

    List<Major> getMajorsList(Long collegeId);

    List<Major> queryMajorsByIdList(Map<String, Object> map);

    List<Major> queryMajorsByPage(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    Major selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKey(Major record);
}