package com.menglin.dao;

import com.menglin.entity.Permission;

import java.util.List;
import java.util.Map;

public interface PermissionDao {

    Permission selectByName(String name);

    List<Permission> getPermissionsList();

    List<Permission> queryPermissionsByPage(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int updateByPrimaryKey(Permission record);
}