package com.menglin.dao;

import com.menglin.entity.StudentCourse;
import org.apache.ibatis.annotations.Param;

public interface StudentCourseDao {

    StudentCourse selectByStudentIdAndCourseId(@Param("studentId") Long studentId, @Param("courseId") Long courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insert(com.menglin.entity.StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insertSelective(com.menglin.entity.StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    com.menglin.entity.StudentCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKeySelective(com.menglin.entity.StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKey(com.menglin.entity.StudentCourse record);
}