package com.menglin.dao;

import com.menglin.entity.StudentTask;
import com.menglin.entity.StudentTaskAllInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface StudentTaskDao {


    StudentTask selectByStudentIdAndTaskId(@Param("studentId") Long studentId, @Param("taskId") Long taskId);

    List<StudentTaskAllInfo> queryStudentTasksByPage(Map<String, Object> map);

    List<StudentTaskAllInfo> queryPendingStudentTasksByPage(Map<String, Object> map);

    List<StudentTaskAllInfo> queryCompletedStudentTasksByPage(Map<String, Object> map);

    List<StudentTaskAllInfo> queryHistoricalStudentTasksByPage(Map<String, Object> map);

    List<StudentTaskAllInfo> queryCorrectingStudentTasksByPage(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_task
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_task
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insert(StudentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_task
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int insertSelective(StudentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_task
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    StudentTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_task
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKeySelective(StudentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_task
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    int updateByPrimaryKey(StudentTask record);
}