package com.menglin.dao;

import com.menglin.entity.Student;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface StudentDao {

    Student selectByUsername(String username);

    List<Student> queryStudentsByIdList(Map<String, Object> map);

    List<Student> selectStudentsByClassTeamIdAndCourseId(@Param("classTeamId") Long classTeamId, @Param("courseId") Long courseId);

    List<Student> selectStudentsByClassTeamId(Long classTeamId);

    List<Student> queryStudentsByPage(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Apr 16 18:22:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Apr 16 18:22:40 CST 2018
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Apr 16 18:22:40 CST 2018
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Apr 16 18:22:40 CST 2018
     */
    Student selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Apr 16 18:22:40 CST 2018
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Apr 16 18:22:40 CST 2018
     */
    int updateByPrimaryKey(Student record);
}