package com.menglin.dao;

import com.menglin.entity.TeacherClassTeam;
import org.apache.ibatis.annotations.Param;

public interface TeacherClassTeamDao {

    TeacherClassTeam selectByTeacherIdAndClassTeamId(@Param("teacherId") Long teacherId, @Param("classTeamId") Long classTeamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_class_team
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_class_team
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int insert(TeacherClassTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_class_team
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int insertSelective(TeacherClassTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_class_team
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    TeacherClassTeam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_class_team
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherClassTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_class_team
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    int updateByPrimaryKey(TeacherClassTeam record);
}