package com.menglin.entity;

import java.util.Date;

public class StudentTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.id
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.student_id
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private Long studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.task_id
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.content
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.url
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.score
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.comments
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.is_delete
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private String isDelete = "N";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.creator
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.modifier
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private String modifier = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.gmt_create
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.gmt_modify
     *
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.id
     *
     * @return the value of student_task.id
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.id
     *
     * @param id the value for student_task.id
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.student_id
     *
     * @return the value of student_task.student_id
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.student_id
     *
     * @param studentId the value for student_task.student_id
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.task_id
     *
     * @return the value of student_task.task_id
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.task_id
     *
     * @param taskId the value for student_task.task_id
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.content
     *
     * @return the value of student_task.content
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.content
     *
     * @param content the value for student_task.content
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.url
     *
     * @return the value of student_task.url
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.url
     *
     * @param url the value for student_task.url
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.score
     *
     * @return the value of student_task.score
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.score
     *
     * @param score the value for student_task.score
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.comments
     *
     * @return the value of student_task.comments
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.comments
     *
     * @param comments the value for student_task.comments
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.is_delete
     *
     * @return the value of student_task.is_delete
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.is_delete
     *
     * @param isDelete the value for student_task.is_delete
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.creator
     *
     * @return the value of student_task.creator
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.creator
     *
     * @param creator the value for student_task.creator
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.modifier
     *
     * @return the value of student_task.modifier
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.modifier
     *
     * @param modifier the value for student_task.modifier
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.gmt_create
     *
     * @return the value of student_task.gmt_create
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.gmt_create
     *
     * @param gmtCreate the value for student_task.gmt_create
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.gmt_modify
     *
     * @return the value of student_task.gmt_modify
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.gmt_modify
     *
     * @param gmtModify the value for student_task.gmt_modify
     * @mbggenerated Tue May 01 19:13:47 CST 2018
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}