package com.menglin.entity;

import java.io.Serializable;
import java.util.Date;

public class Student implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.username
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String grade;

    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.college_id
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Long collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major_id
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Long majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Long classTeamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.is_delete
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String isDelete = "N";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.creator
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.modifier
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String modifier = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gmt_create
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gmt_modify
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.username
     *
     * @return the value of student.username
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.username
     *
     * @param username the value for student.username
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.college_id
     *
     * @return the value of student.college_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Long getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.college_id
     *
     * @param collegeId the value for student.college_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setCollegeId(Long collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major_id
     *
     * @return the value of student.major_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Long getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major_id
     *
     * @param majorId the value for student.major_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setMajorId(Long majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Long getClassTeamId() {
        return classTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classTeamId the value for student.class_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setClassTeamId(Long classTeamId) {
        this.classTeamId = classTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.is_delete
     *
     * @return the value of student.is_delete
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.is_delete
     *
     * @param isDelete the value for student.is_delete
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.creator
     *
     * @return the value of student.creator
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.creator
     *
     * @param creator the value for student.creator
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.modifier
     *
     * @return the value of student.modifier
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.modifier
     *
     * @param modifier the value for student.modifier
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gmt_create
     *
     * @return the value of student.gmt_create
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gmt_create
     *
     * @param gmtCreate the value for student.gmt_create
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gmt_modify
     *
     * @return the value of student.gmt_modify
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gmt_modify
     *
     * @param gmtModify the value for student.gmt_modify
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}