package com.menglin.entity;

import java.io.Serializable;
import java.util.Date;

public class Teacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.username
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.password
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String name;

    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.college_id
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Long collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.is_delete
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String isDelete = "N";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.creator
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.modifier
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private String modifier = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gmt_create
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gmt_modify
     *
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.username
     *
     * @return the value of teacher.username
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.username
     *
     * @param username the value for teacher.username
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.password
     *
     * @return the value of teacher.password
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.password
     *
     * @param password the value for teacher.password
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.college_id
     *
     * @return the value of teacher.college_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Long getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.college_id
     *
     * @param collegeId the value for teacher.college_id
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setCollegeId(Long collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.is_delete
     *
     * @return the value of teacher.is_delete
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.is_delete
     *
     * @param isDelete the value for teacher.is_delete
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.creator
     *
     * @return the value of teacher.creator
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.creator
     *
     * @param creator the value for teacher.creator
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.modifier
     *
     * @return the value of teacher.modifier
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.modifier
     *
     * @param modifier the value for teacher.modifier
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gmt_create
     *
     * @return the value of teacher.gmt_create
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gmt_create
     *
     * @param gmtCreate the value for teacher.gmt_create
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gmt_modify
     *
     * @return the value of teacher.gmt_modify
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gmt_modify
     *
     * @param gmtModify the value for teacher.gmt_modify
     * @mbggenerated Sat Apr 28 16:42:08 CST 2018
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}