package com.menglin.entity;

import java.util.Date;

public class TeacherClassTeam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.id
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.teacher_id
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.class_team_id
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private Long classTeamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.is_delete
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.creator
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.modifier
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.gmt_create
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_class_team.gmt_modify
     *
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.id
     *
     * @return the value of teacher_class_team.id
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.id
     *
     * @param id the value for teacher_class_team.id
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.teacher_id
     *
     * @return the value of teacher_class_team.teacher_id
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.teacher_id
     *
     * @param teacherId the value for teacher_class_team.teacher_id
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.class_team_id
     *
     * @return the value of teacher_class_team.class_team_id
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public Long getClassTeamId() {
        return classTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.class_team_id
     *
     * @param classTeamId the value for teacher_class_team.class_team_id
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setClassTeamId(Long classTeamId) {
        this.classTeamId = classTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.is_delete
     *
     * @return the value of teacher_class_team.is_delete
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.is_delete
     *
     * @param isDelete the value for teacher_class_team.is_delete
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.creator
     *
     * @return the value of teacher_class_team.creator
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.creator
     *
     * @param creator the value for teacher_class_team.creator
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.modifier
     *
     * @return the value of teacher_class_team.modifier
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.modifier
     *
     * @param modifier the value for teacher_class_team.modifier
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.gmt_create
     *
     * @return the value of teacher_class_team.gmt_create
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.gmt_create
     *
     * @param gmtCreate the value for teacher_class_team.gmt_create
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_class_team.gmt_modify
     *
     * @return the value of teacher_class_team.gmt_modify
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_class_team.gmt_modify
     *
     * @param gmtModify the value for teacher_class_team.gmt_modify
     * @mbggenerated Sun May 13 12:10:50 CST 2018
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}